[build]
publish = "public"
command = "mkdir -p public && cp index.html public/"
functions = "functions"


[[redirects]]
  from = "/api/*"
  to = "https://demo.plone.org/++api++/:splat"
  status = 200
  force = true

